"""add_profile_completion_fields

Revision ID: 4bf6b7667eee
Revises: 4d02f6188f8e
Create Date: 2026-01-07 13:20:31.068632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf6b7667eee'
down_revision: Union[str, None] = '4d02f6188f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('founder_profiles', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('founder_profiles', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('founder_profiles', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('founder_profiles', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.add_column('investor_profiles', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('investor_profiles', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.add_column('talent_profiles', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_profiles', 'profile_completed')
    op.drop_column('talent_profiles', 'website')
    op.drop_column('talent_profiles', 'twitter_url')
    op.drop_column('investor_profiles', 'profile_completed')
    op.drop_column('investor_profiles', 'twitter_url')
    op.drop_column('founder_profiles', 'profile_completed')
    op.drop_column('founder_profiles', 'website')
    op.drop_column('founder_profiles', 'twitter_url')
    op.drop_column('founder_profiles', 'company_name')
    # ### end Alembic commands ###
