"""add talent role

Revision ID: 4d02f6188f8e
Revises: 6d24852bb7ca
Create Date: 2026-01-01 19:30:14.712387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d02f6188f8e'
down_revision: Union[str, None] = '6d24852bb7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_pitches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('compensation_type', sa.String(length=20), nullable=True),
    sa.Column('job_title_seeking', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('salary_range_min', sa.Integer(), nullable=True),
    sa.Column('salary_range_max', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=True),
    sa.Column('past_projects', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('certifications', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_preference', sa.String(length=20), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('talent_pitch_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['talent_pitches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent_qa_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['talent_pitches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent_qa_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['talent_qa_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('founder_profiles', sa.Column('talent_views_today', sa.Integer(), nullable=True))
    op.add_column('founder_profiles', sa.Column('talent_views_reset_date', sa.Date(), nullable=True))
    op.add_column('investor_profiles', sa.Column('talent_views_today', sa.Integer(), nullable=True))
    op.add_column('investor_profiles', sa.Column('talent_views_reset_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investor_profiles', 'talent_views_reset_date')
    op.drop_column('investor_profiles', 'talent_views_today')
    op.drop_column('founder_profiles', 'talent_views_reset_date')
    op.drop_column('founder_profiles', 'talent_views_today')
    op.drop_table('talent_qa_messages')
    op.drop_table('talent_qa_threads')
    op.drop_table('talent_pitch_views')
    op.drop_table('talent_profiles')
    op.drop_table('talent_pitches')
    # ### end Alembic commands ###
