"""initial tables

Revision ID: 6d24852bb7ca
Revises: 
Create Date: 2025-12-31 17:15:04.495642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d24852bb7ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('founder_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('seeking_investor_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('desired_check_size_min', sa.Integer(), nullable=True),
    sa.Column('desired_check_size_max', sa.Integer(), nullable=True),
    sa.Column('value_add_preferences', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('investor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('ticket_size_min', sa.Integer(), nullable=True),
    sa.Column('ticket_size_max', sa.Integer(), nullable=True),
    sa.Column('sectors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('stages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('geographies', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('investor_type', sa.String(length=50), nullable=True),
    sa.Column('free_views_remaining', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('question_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('round_size_min', sa.Integer(), nullable=True),
    sa.Column('round_size_max', sa.Integer(), nullable=True),
    sa.Column('traction_bullets', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('apple_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('apple_original_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_transaction_id')
    )
    op.create_table('pitch_unlocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('apple_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_transaction_id'),
    sqlite_autoincrement=True
    )
    op.create_table('pitches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('qa_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['qa_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_messages')
    op.drop_table('qa_threads')
    op.drop_table('pitch_views')
    op.drop_table('pitches')
    op.drop_table('pitch_unlocks')
    op.drop_table('subscriptions')
    op.drop_table('startups')
    op.drop_table('question_templates')
    op.drop_table('investor_profiles')
    op.drop_table('founder_profiles')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
