"""add_preferred_sectors_to_talent

Revision ID: 73b01b5022d8
Revises: 4bf6b7667eee
Create Date: 2026-01-07 13:51:29.497416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b01b5022d8'
down_revision: Union[str, None] = '4bf6b7667eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent_profiles', sa.Column('preferred_sectors', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_profiles', 'preferred_sectors')
    # ### end Alembic commands ###
