"""add thread status and decline message

Revision ID: e6a866cf2058
Revises: ad656677e499
Create Date: 2026-01-09 14:32:02.565828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a866cf2058'
down_revision: Union[str, None] = 'ad656677e499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_threads', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('qa_threads', sa.Column('decline_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_threads', 'decline_message')
    op.drop_column('qa_threads', 'status')
    # ### end Alembic commands ###
